### ISSUE TITLE
ObjectGraphWalker throws the wrong exception type when max depth exceeded

### ISSUE THREAD

**Issue by kennymacleod** [ehcache/sizeof#28]
When ObjectGraphWalker exceeds the max depth, it throws an IllegalArgumentException. However EhcacheSizeOfEngine is expecting to catch a MaxDepthExceededException. The IllegalArgumentException bubbles up past that catch  and a stack trace is logged.

This is odd, given that the sizeof engine in EhCache 2.8 throws the correct MaxDepthExceededException.

**Comment by alexsnaps** [comment]
If the "feature" is required now, it needs to be implemented using the VisitorListener (see #10)
